// Code generated by goctl. DO NOT EDIT!
// Source: sub.proto

package server

import (
	"context"

	"bookstore/rpc/sub/internal/logic"
	"bookstore/rpc/sub/internal/svc"
	"bookstore/rpc/sub/sub"
)

type SuberServer struct {
	svcCtx *svc.ServiceContext
}

func NewSuberServer(svcCtx *svc.ServiceContext) *SuberServer {
	return &SuberServer{
		svcCtx: svcCtx,
	}
}

func (s *SuberServer) Check(ctx context.Context, in *sub.SubReq) (*sub.SubResp, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
